### ISSUE TITLE
one submodule uses ssh instead of https

### ISSUE THREAD

**Issue by vicenteg** [OldCrowEW/dcos-ansible#14]
Hi, thanks for sharing this repo. Cloning fails with permission denied because one of the submodules uses `git@github.com` instead of https:

```
[submodule "roles/ansible-dcos-bootstrap-node"]
        path = roles/ansible-dcos-bootstrap-node
        url = git@github.com:OldCrowEW/ansible-dcos-bootstrap-node.git
```

I was able to work around it by manually changing .gitmodules and resyncing, but it would be easier if all the subs used https.

Thanks!

**Comment by OldCrowEW** [comment]
I didn't realize it was causing others issues. I have made your recommended change. Thanks for letting me know!
